name: ✨ Add functionality | Feature Request
description: Come up with a new idea or suggestion for this project | Suggest a new idea for this project
title: "[Feature]: "
labels:
  - enhancement

body:
  - type: textarea
    attributes:
      label: Requirement description | Problem Statement
      description: |
        Please describe the problem or need you wish to solve 
        Please describe the problem you want to solve
      placeholder: |
        I encountered during use...
        I encountered... when using this project
    validations:
      required: true
  - type: textarea
    attributes:
      label: Suggested solution | Proposed Solution
      description: |
        Please describe a possible solution or implementation that you think is possible
        Please describe your suggested solution or implementation
      placeholder: |
        You can consider adding...function to solve this problem
        Consider adding... feature to address this issue
    validations:
      required: true